name: space_scutum
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  go_router: ^17.0.0
  get_it: ^9.1.1
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  injectable: ^2.7.0
  flutter_svg: ^2.2.3
  flutter_dotenv: ^6.0.0
  retrofit: ^4.9.0
  logger: ^2.6.0
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  drift_dev: ^2.29.0
  injectable_generator: ^2.9.1
  flutter_lints: ^6.0.0
  retrofit_generator: ^10.0.1
  sqlite3_flutter_libs: ^0.5.41

flutter:

  uses-material-design: true

  assets:
    - assets/no_data.svg
    - .env
  #   - images/a_dot_ham.jpeg
